### ISSUE TITLE
Unable to use full height of window

### ISSUE THREAD

**Issue by josswright** [junegunn/goyo.vim#100]
I'm calling Goyo with ":Goyo 120-100%x100%-100%" with the intention of having it left-aligned and running from the top of the window to the bottom. No matter what I do, however, there seems to be a margin at the top and bottom of two lines.

I found  g:goyo_margin_bottom and g:goyo_margin_top, but setting those to 0 (or, in fact, any other value) doesn't seem to change this behaviour.

I have a relatively minmial plugin setup, so there's unlikely to be any interaction with status bars or other plugins.

**Comment by junegunn** [comment]
> No matter what I do, however, there seems to be a margin at the top and bottom of two lines.

Due to how Goyo is implemented (4 invisible padding windows around the central window), it's impossible to completely remove the margins. Maybe I should mention this limitation in the doc.

> I found g:goyo_margin_bottom and g:goyo_margin_top, but setting those to 0 (or, in fact, any other value) doesn't seem to change this behaviour.

Those parameters are deprecated, thus undocumented.

**Comment by josswright** [comment]
Ah, I understand it now given that explanation.

Having looked over the code, I've commented out all the lines that create or manipulate t:goyo_pads.b and t_goyo_pads.t. For the moment, that seems to be working for me. I could just leave it like that in my version.

I could probably, with a little more work, formalise this slightly so that if the height is set to 100% or a margin_bottom or margin_top parameter are set to 0 then it would just disable the creation of those pads.

Before I bother doing that, can you think of any obvious problems that that might cause?

**Comment by junegunn** [comment]
Goyo allows you to dynamically change the size of the window with `[count]<CTRL-W>` + `>`, `<`, `+`, which means we have to dynamically create or remove the pads.

**Comment by nielsaka** [comment]
> Having looked over the code, I've commented out all the lines that create or manipulate t:goyo_pads.b and t_goyo_pads.t. For the moment, that seems to be working for me. I could just leave it like that in my version.

I have done the same. Specifically these lines

    " \ || bufwinnr(t:goyo_pads.b) <= bufwinnr(t:goyo_pads.t) + 3
    ...
    " call s:setup_pad(t:goyo_pads.t, 0, top, 'j')
    " call s:setup_pad(t:goyo_pads.b, 0, bot, 'k')
    ...
    " let t:goyo_pads.t = s:init_pad('topleft new')
    " let t:goyo_pads.b = s:init_pad('botright new')

Now the height is permanently fixed to 100%
