### ISSUE TITLE
s:hide_statusline executes after autocmd user s:GoyoEnter ?

### ISSUE THREAD

**Issue by sdothum** [junegunn/goyo.vim#101]
From what I can tell the goyo.vim s:hide_statusline function executes after my autocmd user s:GoyoEnter. I was trying to enable a simple statusline to show while navigating around my vimwiki database and could only get this to work by commening out the 

" let &l:statusline = repeat(' ', winwidth(0))

of the hide function so my statusline wouldn't be overwritten. Luckily for me, in my initial testing, this does not appear cause any problems with goyo :-)

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/goyo.vim/issues/88#issuecomment-172201473

`s:hide_statusline` is needed to suppress fancy statusline plugins like airline. If you don't use one, commenting out the line will not cause any problem.

**Comment by sdothum** [comment]
Thanks for confirming this. Other than that, have been using goyo for dfm writing for quite some time (it's only recently that I started playing with a simple statusline -- I toggle various minimalist statuslines, one of which is just a single centered utf-8 char to let me know that the buffer has been modified).
