### ISSUE TITLE
Goyo resets user-overridden styles

### ISSUE THREAD

**Issue by SaswatPadhi** [junegunn/goyo.vim#103]
I use `solarized` colorscheme but I have overridden parts of it (line highlighting etc).

Goyo resets these because of: [autoload/goyo.vim#L335](../blob/master/autoload/goyo.vim#L335); every time user leaves Goyo.
In stead of resetting the whole colorscheme, can we keep track of which features we turn off when enabling Goyo; and reset them to their original values?

**Comment by junegunn** [comment]
> can we keep track of which features we turn off when enabling Goyo; and reset them to their original values?

It's complicated and hacky and I would not do that. Your customization of colors will be lost whenever you switch colorschemes, so I recommend that you make sure that it's reapplied on `ColorScheme` event.

See #84 for the solution.

**Comment by SaswatPadhi** [comment]
I see. But my thoughts were, we only tweak a few parts of the entire colorscheme -- and they are already hard-coded (like `nocursorline` etc.). So we could keep track of these and reapply them.

I'm just wondering why would it be too hacky?

**Comment by junegunn** [comment]
The thing I was confused about is that I thought there was no API to get the properties of a highlight group – I used to parse the output of `:hi` command in some other plugins which is the process I referred to as hacky – but it does exist and Goyo is already using it. So yes, it's doable, but it's still much simpler for me to just reload the colorscheme :) And custom colors disappearing on color scheme change is almost always not intended and it's not a bad idea to make it right first.

Another minor concern is that we cannot know whether if there are additional colors that are manually updated for Goyo environment by the user in `GoyoEnter` event. Not reloading color scheme will break backward compatibility in that case and the user will have to update `GoyoLeave` callback to reload the color scheme on exit.

**Comment by SaswatPadhi** [comment]
Thanks for the details! Here are my thoughts on it:

> The thing I was confused about is that I thought there was no API to get the properties of a highlight group – I used to parse the output of :hi command in some other plugins which is the process I referred to as hacky – but it does exist and Goyo is already using it. So yes, it's doable, but it's still much simpler for me to just reload the colorscheme :) And custom colors disappearing on color scheme change is almost always not intended and it's not a bad idea to make it right first.

Well I would be happy to send a PR :-)
The thing that concerns me is, the user does not expect the colorscheme (or other settings) to change when turning Goyo on and off. At least we should add a section in the README otherwise -- informing users that they should add any colorscheme modifications to GoyoLeave.

> Another minor concern is that we cannot know whether if there are additional colors that are manually updated for Goyo environment by the user in GoyoEnter event. Not reloading color scheme will break backward compatibility in that case and the user will have to update GoyoLeave callback to reload the color scheme on exit.

This is fixable though. What I was proposing was:
_GoyoEnter_:
1. Save old colors
2. Change to colors specific to Goyo environment
_GoyoExit_:
1. Reload colorscheme (to override colors for Goyo environment)
2. Reapply saved color values (to make sure the old environment is consistent)

**Comment by junegunn** [comment]
> Well I would be happy to send a PR :-)

Fine with me.

> At least we should add a section in the README otherwise -- informing users that they should add any colorscheme modifications to GoyoLeave.

Or on ColorScheme event as suggested in https://github.com/junegunn/goyo.vim/issues/84#issuecomment-156299446, which is the most robust solution.

> This is fixable though

I'm just saying that it's a change of behavior (for better or worse) that breaks backward compatibility for some users who expect their color customization in `GoyoEnter` is reverted automatically. Just a minor annoyance.

**Comment by SaswatPadhi** [comment]
I see. Yep, agreed.

Thanks.
