### ISSUE TITLE
Goyo not hiding statusline

### ISSUE THREAD

**Issue by aratno** [junegunn/goyo.vim#109]
Hello,

I just installed lightline.vim and I've been really liking it. Until I realized it broke goyo. This is what I see now:
<img width="1440" alt="screenshot 2016-04-07 22 59 42" src="https://cloud.githubusercontent.com/assets/8835036/14373091/9563be36-fd14-11e5-879e-ea77692d2676.png">

I thought goyo would automatically hide lightline, but it doesn't seem to be working. Any ideas? 
Here's my system information:
````
OS: 64bit Mac OS X 10.11.1 15B42
Kernel: x86_64 Darwin 15.0.0
Uptime: 16d 8h 27m
Packages: 141
Shell: zsh 5.0.8
Resolution: 2880x1800
DE: Aqua
WM: Quartz Compositor
WM Theme: Graphite
Font: InputMonoCondensed-Light 12
CPU: Intel Core i7-4750HQ CPU @ 2.00GHz
GPU: Intel Iris Pro
RAM: 5215MiB / 8192MiB
````

**Comment by junegunn** [comment]
Probably related: https://github.com/junegunn/goyo.vim/commit/9cea5e5c7dcf2bcc05c9f63d88212919407cf193

Update Goyo and see it helps, I can't reproduce here.

**Comment by aratno** [comment]
Works now, thanks!
