### ISSUE TITLE
how to set   g:goyo_width   with precent ?

### ISSUE THREAD

**Issue by epirus** [junegunn/goyo.vim#112]
it's my  Goyo Toggle  map
nnoremap <silent> <leader>z :Goyo <cr>

so i dont't want to use Goyo 80%

it seems that    g:goyo_width  don't support with percent~

![dog-jet-ski-aiE3JQU3vLqTK](https://media4.giphy.com/media/aiE3JQU3vLqTK/giphy.gif)

**Comment by junegunn** [comment]
It works as expected:

```
let g:goyo_width = '50%'
```
