### ISSUE TITLE
Apply it on a per-buffer basis

### ISSUE THREAD

**Issue by gnapse** [junegunn/goyo.vim#113]
I found out about this vim plugin when looking for a way to soft-wrap a vim buffer to a specific width. So in reality I do not need all of its functionality, but even with all the extra stuff, it fits my need. Except for one thing: I'd like to be able to apply this to a specific buffer, but not to all of my open buffers. Is there a way to use it like this?

**Comment by junegunn** [comment]
Unfortunately, no. It's not what this plugin is designed for.
