### ISSUE TITLE
How to leave Goyo automatically before saving session on VimLeave

### ISSUE THREAD

**Issue by azag0** [junegunn/goyo.vim#115]
I have the following autocmd set, which automatically saves a vim session on quitting vim.
```vim
        autocmd VimLeave * call SaveSession(FindProjectName())
```
This doesn't play well with Goyo, since a Goyo tab isn't really restored properly from the session metadata. So it would make more sense to leave Goyo automatically (since I of course forget to do it manually and then have to `:tabclose` on entering the session) before this autocmd is executed. I tried to define the following autocmd *before* the one above, but that doesn't seem to work.
```vim
        autocmd VimLeave * nested call <SID>goyo_leave()
```
Any ideas how to make this work?

**Comment by junegunn** [comment]
I don't use sessions, but as far as I know, a session does not store the complete snapshot of the state (open up the stored session file and you'll notice), and I'm doubtful that it can be used to "resurrect" Goyo mode.

**Comment by junegunn** [comment]
Anyway, back to your question, I'm not sure why you put `goyo_leave` there. Have you tried `Goyo!` instead (the command to close Goyo tab if it's open)?

**Comment by azag0** [comment]
Yes, I didn't mean to say that it's a bug that Goyo doesn't get restored, the session data are relatively limited I believe.

As for your suggestion, eh, yes, I have no clue why I thought what I did should work, while yours work perfectly! Thanks. I didn't realize that that function is only a user hook called by :Goyo!.
