### ISSUE TITLE
Statusline not hidden after buffer change with :bn or :bp

### ISSUE THREAD

**Issue by christian-titze** [junegunn/goyo.vim#116]
![goyo](https://cloud.githubusercontent.com/assets/2010034/15283519/7f6b02d8-1b4b-11e6-9427-13cdcaa39ea5.png)

I already tried to narrow this problem down to one of my plugins but with no luck. Maybe someone here will know how to fix it. Steps to reproduce:
1. Start vim with any file
2. Start goyo
3. Create new buffer, e.g. with :bad hello.txt
4. Switch between buffers multiple times with :bn and :bp
5. Unwanted statusline with filename and other information appears in bottom left corner

(My vimrc can be found here: https://github.com/christian-titze/dotfiles-ng/blob/master/nvim/init.vim)

**Comment by junegunn** [comment]
Well, it's not something Goyo hides, so it's not unexpected. Just hit <kbd>CTRL-L</kbd> to clear the message if it bothers you, or you can probably set up an autocmd to do that when you insert Goyo mode.
