### ISSUE TITLE
Use goyo to center buffer

### ISSUE THREAD

**Issue by etiennebatise** [junegunn/goyo.vim#118]
Hi,

First, thank you for your nice plugin! I have recently changed my computer screen to a much wider one and I find myself using Goyo only to center my buffer on the screen. I like to have only one buffer displayed at once but now I miss a lot of stuff (like my statusline and some other stuff that goyo disable by defaults). 

So my question is: Is there an easy way to use goyo to only center the buffer. Let me know if I'm not clear.

**Comment by junegunn** [comment]
> I miss a lot of stuff

Goyo is a special mode ("hack" would be the precise term) that is not compatible with many plugins; fancy statusline plugins like airline or lightline, and plugins that create temporary splits. You can restore the color of the statusline in your GoyoEnter callback (e.g. `hi statusline ctermfg=red | set statusline=%f`), but beyond that, many things will not work as expected and you'll be frustrated.

**Comment by etiennebatise** [comment]
Ok, I understand 👍 

I think I am going to write a script to do what I need. I've seen few propositions telling to simply open two empty buffers on both sides and change the buffers edges colours the background. It seems a bit dirty hacky still, but I am actually doing that by hand already so why not. Thank you for your time anyway.

**Comment by junegunn** [comment]
> open two empty buffers on both sides and change the buffers edges colours the background

Actually that's a part of the trick Goyo does and that's why Goyo doesn't work well with the plugins that create splits. I would consider using tmux panes to achieve the same effect. Tmux is as programmable and does not interfere with Vim plugins.

**Comment by etiennebatise** [comment]
Well I use vim-tmux setup a lot already, why not. I feel like having a command line available on both side will bug me a bit.
