### ISSUE TITLE
Statusline visible when using setting in Airline

### ISSUE THREAD

**Issue by guyfedwards** [junegunn/goyo.vim#119]
Using `let g:airline_skip_empty_sections = 1` in airline causes the statusline to show after a brief delay when running `:Goyo`. The option was added recently to Airline to allow separators to be hidden if a section is empty, https://github.com/vim-airline/vim-airline/pull/1130.

I'm guessing the airline is reenabled after it checks if a section is empty, thus overriding `Goyo`s disabling of it?

Nvim 0.1.3
![image](https://cloud.githubusercontent.com/assets/1794071/16000835/99a1ad6c-3146-11e6-82a6-ea822eff312e.png)

**Comment by ninrod** [comment]
I had a similar issue until 50 seconds ago. Try to update lightline to HEAD.

**Comment by guyfedwards** [comment]
@ninrod using airline unfortunately

**Comment by ninrod** [comment]
oh, sorry. try to airline HEAD though, if you didn't already.

**Comment by junegunn** [comment]
@guyfedwards You should report this to airline issue tracker. This can be reproduced without Goyo.

```vim
AirlineToggle
" wait ...
```
