### ISSUE TITLE
Ruler not working in Goyo mod

### ISSUE THREAD

**Issue by nzmi** [junegunn/goyo.vim#120]
Thank you for your amazing plugin! I like it so much!

But I have a little trouble.
When I use "Goyo", ruler always shows "0,0 -1".
![screen shot 2016-06-25 at 16 32 33](https://cloud.githubusercontent.com/assets/18674593/16356471/d0b05174-3afa-11e6-892d-97589c29cb6c.png)

**Comment by junegunn** [comment]
Sorry for the late reply. Unfortunately I don't think we can fix this as it's the limitation of Vim. The numbers you see at the bottom right of the screen is from the invisible "padding" window below the central window. You'll see what's going on behind the curtain with the following script:

```vim
hi StatusLine ctermbg=red guibg=red
hi StatusLineNC ctermbg=blue guibg=blue
hi VertSplit ctermbg=green guibg=green
set ruler statusline=
```
