### ISSUE TITLE
Retain CursorLine highlighting when exiting Goyo

### ISSUE THREAD

**Issue by facingBackwards** [junegunn/goyo.vim#122]
CursorLine highlight settings appear to get reset when leaving Goyo. I have the following in vimrc to highlight but not underline the current line

    set cursorline
    hi CursorLine ctermbg=188 ctermfg=NONE cterm=NONE term=NONE

Entering Goyo works as expected (current line is highlighted) but leaving back to normal mode resets the highlight colours and turns the underline on. Ideally the settings would not be changed either entering or leaving Goyo.

    :hi CursorLine
    CursorLine     xxx term=underline cterm=underline guibg=Grey90

Is it possible to retain the highlight settings?

**Comment by junegunn** [comment]
Please refer to the comments here: https://github.com/junegunn/goyo.vim/issues/84#issuecomment-156299446

**Comment by facingBackwards** [comment]
So this is because it's a custom change rather than part of  a colour scheme? I'll add the `autocmd`s in.

Thanks
