### ISSUE TITLE
give example in the readme

### ISSUE THREAD

**Issue by teto** [junegunn/goyo.vim#130]
Like

```
let g:goyo_linenr=1
let g:goyo_height= '90%'
let g:goyo_width = 120
```

at first I tried "let g:goyo_height=0.90" as using a string seemed awkward but that didn't work.

I never thought I would rely on such a plugin but this proves very helpful when writing my thesis. Thanks !

**Comment by valentjedi** [comment]
Agree. Without this issue, I couldn't figure it out. I've tried string with double quotes, but it didn't work for me. I guess it has to be something in vimscript that I don't know.
