### ISSUE TITLE
Does not remember last place in file

### ISSUE THREAD

**Issue by robmuh** [junegunn/goyo.vim#131]
This is extremely annoying when working on large documents, which is what Goyo is so good at helping with otherwise.

**Comment by junegunn** [comment]
See #27. Due to the limitation of Vim, it doesn't work if you close Goyo window with `:q` or `:close`. It'll work if you close Goyo with any of the followings

- `:Goyo` (it's a toggle command)
- `:tabclose`
- `gt`
