### ISSUE TITLE
height

### ISSUE THREAD

**Issue by GianniGi** [junegunn/goyo.vim#133]
I'm not able to make this work... I'd like the margins to be as small as possible

" Goyo Setup {{{
let g:goyo_margin_top = 2
let g:goyo_margin_bottom = 2

**Comment by junegunn** [comment]
Where did you get those options? They're deprecated and not documented anywhere on the code.

Anyway try `let g:goyo_height = '100%'`, but even then there will be one margin at the top and the bottom. It's a limitation of the current implementation.

**Comment by paldepind** [comment]
> Where did you get those options? They're deprecated and not documented anywhere on the code.

They're still visible in the screenshot in the readme.

**Comment by junegunn** [comment]
<img width="1280" alt="goyo2019" src="https://user-images.githubusercontent.com/700826/53289067-5f1f6c00-37d4-11e9-9c72-f8643111e520.png">

Thanks, time for an update.

**Comment by paldepind** [comment]
Looks good :+1: Btw, I found this issue because I set `let g:goyo_height = '100%'` and was wondering why I still had a bit of margin in the top and bottom. Maybe it would be nice to mention this in the readme. I can do a PR if you're interested.

**Comment by xukongwen** [comment]
How can I totally disable the margin in top and bottom?
