### ISSUE TITLE
Hide tmux bar

### ISSUE THREAD

**Issue by mastertinner** [junegunn/goyo.vim#138]
Thanks so much for all your awesome plugins, @junegunn!
Is there a way to automatically hide the tmux bar when in Goyo mode? Or would that even be something to be added to Goyo (so the bar would be hidden just like the airline bar)?

**Comment by junegunn** [comment]
You can find how to do it in the example shown in https://github.com/junegunn/goyo.vim#callbacks

**Comment by mastertinner** [comment]
Thanks, @junegunn! And sorry for not reading that properly before posting a question.
