### ISSUE TITLE
Vim 7.4 - Interface highlighting problem

### ISSUE THREAD

**Issue by tranquillemartin** [junegunn/goyo.vim#142]
Before goyo starting  (everything fine) :
![01](https://cloud.githubusercontent.com/assets/24791015/23585767/28976604-0187-11e7-9d52-3f3648b4b2d8.png)

During goyo use (everything fine) :
![02](https://cloud.githubusercontent.com/assets/24791015/23585775/47ae011a-0187-11e7-8c4b-1852ef76795a.png)

After goyo use (the whole interface is highlighted) :
![03](https://cloud.githubusercontent.com/assets/24791015/23585781/67366da6-0187-11e7-8192-e7d186687ad7.png)

If you know any work around ...

Thanks and regards,

**Comment by junegunn** [comment]
It's an issue of your particular configuration, and I'm not sure if I can really help you with that. My guess is that you have `set background=dark` in your configuration file after the line loading your color scheme. Goyo reloads the current color scheme on exit, and you may have to `set background=dark` in GoyoLeave event.

https://github.com/junegunn/goyo.vim#callbacks

**Comment by core-engineering** [comment]
Thanks for your reply, I will investigate in the way you indicate.
