### ISSUE TITLE
Add help doc

### ISSUE THREAD

**Issue by devth** [junegunn/goyo.vim#145]
This plugin should have a standard `doc/goyo.txt` that documents its available usage and configuration.

**Comment by ultimatecoder** [comment]
Hey @devth,
    I have prepared the documentation file for this plugin. Please find it here https://gist.github.com/ultimatecoder/491e6da43f2f796446068d427f6668bc

Please let me know if you need any help in adding this plugin to your vim and generating tags file for it. Thanks!

**Comment by junegunn** [comment]
Added help file which is the direct result of README.md conversion. Like I mentioned in #144, I don't want to maintain two versions of the documentation, so I believe this is my decision. The help file of @ultimatecoder seems to contain more information, so if you need that version you can still install it as well.
