### ISSUE TITLE
Pathogen installation results in E492: not an Editor command : goyo

### ISSUE THREAD

**Issue by PandaPony** [junegunn/goyo.vim#147]
Hi

Cloned to my vimfiles folder using pathogen. Now I have C:\Users\joe\vimfiles\bundle\goyo.vim alongside other -working- plugins. However executing `:goyo` results in  
`E492: not an Editor command : goyo`  

Any ideas?

**Comment by ultimatecoder** [comment]
@PandaPony You should try launching plugin with `:Goyo` (Observe the Camelcase)

**Comment by PandaPony** [comment]
Awesome :1st_place_medal Thanks @ultimatecoder
