### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by caedn** [junegunn/goyo.vim#149]
Any chance you can add any? I like this plugin but the possible arguments are not exactly intuitive. I find myself googling `goyo vim` a lot when I could just take a quick peek with `help`.

**Comment by rafaeln** [comment]
Man, you should really just add to the README a link to that other repo
where people have been converting the readme into a vimhelp file, with
the caveat that it might not be completely up-to-date. This is of course
just advice. It's free and you're free from having to pay any heed to
it, but a vimhelf file seems to be a common request...

**Comment by ultimatecoder** [comment]
Hi, You can find vim specific helpfile for this plugin https://github.com/ultimatecoder/goyo-doc

**Comment by junegunn** [comment]
https://github.com/junegunn/goyo.vim/commits/master
