### ISSUE TITLE
Redraw after terminal window resize

### ISSUE THREAD

**Issue by timofurrer** [junegunn/goyo.vim#159]
Would it be possible to redraw the goyo window when the terminal window is resized? 
This is especially useful when specifying the *width* and heights* in percentages.

**Comment by junegunn** [comment]
You can do it manually by pressing `CTRL-W` + `=`. Currently I'm not triggering it automatically since it's not clear if it's always desirable as the user can manually adjust the size of the central window by pressing `CTRL-W` + [`>`, `<`, `+`, `-`].

**Comment by henrebotha** [comment]
@junegunn Would you consider a config option to enable automatic resize? Or a callback hook even.

**Comment by timofurrer** [comment]
@junegunn That actually works pretty good!

> @junegunn Would you consider a config option to enable automatic resize? Or a callback hook even.

I'd love to see that, too! Even if it's a by-default disable option one could turn on.

**Comment by henrebotha** [comment]
For those who share my preferences, you can stick this in your `.vimrc`:

```vimrc
" On window resize, if goyo is active, do <c-w>= to resize the window
autocmd VimResized * if exists('#goyo') | exe "normal \<c-w>=" | endif
```

**Comment by tgirod** [comment]
@henrebotha thanks! I wonder why this is not the default behaviour.

**Comment by astier** [comment]
I think this should be the default behavior.
