### ISSUE TITLE
:q only disables Goyo

### ISSUE THREAD

**Issue by ghost** [junegunn/goyo.vim#16]
Hi,

First of all, this is an excellent plugin. There's just one minor problem I'm having with it, it's that when Goyo is active `:q` doesn't quit but simply closes Goyo. Therefore two quits are needed to really quit. I've "fixed" it this way but I'm thinking maybe there is a cleaner way to do it?

```
" Quitting whether Goyo is active or not
ca wq :w<cr>:call Quit()<cr>
ca q :call Quit()<cr>
function! Quit()
    if winnr('$') > 3
        Goyo
    endif
    quit
endfunction
```

What do you think?

Thank you and best regards,
Maxime.

**Comment by kminh** [comment]
I'm trying out the suggestion on the wiki page, if I type `:q` when there are unsaved changes, the warning message is not shown:
![screenshot from 2015-11-12 23-47-56](https://cloud.githubusercontent.com/assets/6402124/11124491/e27be766-8997-11e5-8f04-d9f74887890e.png)
Not sure if this is expected?

**Comment by junegunn** [comment]
@kminh Then Goyo is closed but you still stay in Vim, right? I didn't intend it but I don't know how to "fix" it. Let me know if you find a workaround.

**Comment by kminh** [comment]
@junegunn Vim is closed as well if that's the last buffer, so everything seems correct except that the warning message ("Save changes to ....? Yes, No, Cancel") is not shown under ":q". It seems to be hidden somewhere (perhaps in the original tab?)
