### ISSUE TITLE
Visible borders framing text

### ISSUE THREAD

**Issue by AichP** [junegunn/goyo.vim#161]
Hi, for some reason goyo draws borders around the text area. Looks Like [this](https://i.imgur.com/SZjLcNN.png).
I'm using gvim.

**Comment by junegunn** [comment]
Not all color schemes are compatible with Goyo. Try again with different color schemes and see if it helps.

**Comment by AichP** [comment]
Coult it be because of the transparent terminal background?

**Comment by junegunn** [comment]
Yeah, that could be it. Goyo overrides the colors so that the foreground color and the background are the same (see `:hi VertSplit`). I guess the trick won't work nicely with transparent background.

**Comment by AichP** [comment]
This Setup seems to work with transparent backgound though:
https://www.reddit.com/r/unixporn/comments/6vdf4y/i3wm_my_latex_editing_setup/

**Comment by junegunn** [comment]
I don't use transparent background, so I don't really know. I'll check it when I get a chance.

**Comment by AichP** [comment]
Cool, thanks I'll fiddle with my color scheme.

**Comment by AichP** [comment]
I conacted the creater of the reddit post, and he advised me to try it with urxvt. And thats what I did, your plugin workes well with urxvt but does seem to not work with termite.

**Comment by junegunn** [comment]
I see, thanks for the update.
