### ISSUE TITLE
Break colorscheme when toggle Goyo

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/goyo.vim#162]
When I switch to Goyo while limelight is being enabled, colors highlight correct, but if I toggle to turn off Goyo (:Goyo in vim), colorschem's broken. I have to reload .vimrc to get back colorscheme. This mean Goyo call limelight after turn off but doesn't touch colorcheme. I'm using material-theme.

Any thoughts?

**Comment by tuyenpm9** [comment]
Even limelight is not enabled, toggle Goyo will break colorscheme anyway.

**Comment by junegunn** [comment]
Related issues can be found here:

https://github.com/junegunn/goyo.vim/search?q=autocmd+colorscheme&type=Issues&utf8=%E2%9C%93
