### ISSUE TITLE
Cant disable plugin 'buftabline' when opening Goyo

### ISSUE THREAD

**Issue by nielsrasmus** [junegunn/goyo.vim#171]
Hi,

thanks for your beautiful work with goyo, using it every day :+1: 

The only thing I just cant figure out is how to disable the plugin [buftabline](https://github.com/ap/vim-buftabline/blob/master/doc/buftabline.txt)

I have this in my .vimrc 

    function! s:goyo_enter()
      let g:buftabline_show = 0
      " ...
    endfunction
    
    function! s:goyo_leave()
      let g:buftabline_show = 2 
      " ...
    endfunction
    
    autocmd! User GoyoEnter call <SID>goyo_enter()
    autocmd! User GoyoLeave call <SID>goyo_leave()

But I just cant get it to work!

I have tried `let g:buftabline_show = 0`without the goyo function and that works as expected. Just not together with goyo though.

The rest of my .vimrc are [here](https://gist.github.com/nielsrasmus/c3a4bff69d65c4e8bd506b00112027ce):

Below a screenshot with the buftabline that I dont want to have when using goyo.

Any ideas?

![skaermbillede fra 2018-01-20 11-09-57](https://user-images.githubusercontent.com/4162590/35183433-5ce02426-fde6-11e7-91e8-a3eba8f8bdcb.png)

**Comment by junegunn** [comment]
I don't know anything about the plugin so this is really not something I can answer. But see 
 https://github.com/ap/vim-buftabline/blob/master/doc/buftabline.txt#L26-L28

**Comment by AxelBohm** [comment]
I have more or less the same issue and don't know how the previous comment answers this. The problem is, even if I have the buftabline disabled (let g:buftabline_show=0) but merely installed I see the above behaviour (+ lorem.md 5+ lorem.md appearing on top).

**Comment by vigilancer** [comment]
Confirm.
Problem is inside `buftabline`.
Anyone in search for solution please see my [PR](https://github.com/ap/vim-buftabline/pull/67).

**Comment by AxelBohm** [comment]
hey @vigilancer, thanks for the PR. When I disable buftabline, i.e. `let g:buftabline_show=0`, everything works as intended. However, when enabled the same problem persists, are you aware of this fact?

**Comment by vigilancer** [comment]
@AxelBohm I think it would be more appropriate to discuss PR in related repository.
