### ISSUE TITLE
Add option to draw thin border framing text area

### ISSUE THREAD

**Issue by BlueDrink9** [junegunn/goyo.vim#176]
Plugin is marvellous, but I find it really disconcerting to have the text totally floating, without any idea of where it will wrap or where it will hit the bottom of the screen.

Would it be possible to draw/leave a thin border around the text entry area?

**Comment by leontepe** [comment]
I would like to request the same feature. Quite confusing, especially when you're in parts of code that are indented 2-3 levels. You can't really see where the base identation starts.

**Comment by junegunn** [comment]
This is technically not possible as @arzg explained.
