### ISSUE TITLE
goyo status variable

### ISSUE THREAD

**Issue by Konfekt** [junegunn/goyo.vim#180]
I am trying to reconcile the  autocmd
```vim
  autocmd VimEnter * let t:startify_new_tab = 1
  autocmd BufWinEnter *
        \ if !exists('t:startify_new_tab') && (empty(expand('%')) && empty(&l:buftype) && &l:modifiable) |
        \   let t:startify_new_tab = 1 |
        \   Startify |
        \ endif
```
that opens `Startify` from https://github.com/mhinz/vim-startify/ on every new tab page with goyo vim. However, this will throw the error
```vim
Error detected while processing function goyo#execute[7]..<SNR>366_goyo_on[92]..<SNR>366_resize_pads[19]..<SNR>366_setup_pad:
line   13:
W10: Warning: Changing a readonly file
E474: Invalid argument
```

 The best I could come up with is detecting if Goyo is running by its tab variables, such as `t:goyo_master`, so that 
```vim
autocmd BufWinEnter *
        \ if !exists('t:startify_new_tab') && (empty(expand('%')) && empty(&l:buftype) && &l:modifiable && !exists('t:goyo_master')) |
        \   let t:startify_new_tab = 1 |
        \   Startify |
        \ endif
```
works. But perhaps there is a documented status indicator if Goyo is running? Or does perhaps the callback function provided by Goyo allow for avoiding Startify on going Goyo?

**Comment by junegunn** [comment]
> detecting if Goyo is running by its tab variables, such as `t:goyo_master`

It's undocumented, but I don't have any plan to remove the variable. So you're safe to use `exists('t:goyo_master')`.
