### ISSUE TITLE
Help with resizing goyo and NERDTree

### ISSUE THREAD

**Issue by thisconstantreader** [junegunn/goyo.vim#193]
Hello I am needing some help with resizing goyo after I toggle NERDTree.

I am wanting to be able to toggle NERDTree on and off while using goyo and have the size automatically reset for goyo. I have this working for undotree using the below code. I just don't know how to do it for NERDTree. Can anybody help?

" === UndoTree
" using relative positioning instead
let g:undotree_CustomUndotreeCmd = 'vertical 32 new'
let g:undotree_CustomDiffpanelCmd = 'belowright 12 new'

**Comment by thisconstantreader** [comment]
All this can be closed now. I found nnoremap <F1> :NERDTreeToggle<cr>:Goyo x<cr> and this does exactly what I was needing. :)

**Comment by junegunn** [comment]
Or you can hit `CTRL-W =`.
