### ISSUE TITLE
How to open file directly in Goyo?

### ISSUE THREAD

**Issue by ipsod** [junegunn/goyo.vim#194]
Is it possible to open a file directly in Goyo?

I'd like to

- `$ vim file1`
- `:Goyo file2`
- there are now only two windows: `file1`, and the Goyo `file2` window.
- closing the Goyo window, there is no `file2` window left open, and I'm back on `file1`

**Comment by jxpp** [comment]
From the command line, it's possible to tell vim which commands to run when it opens with the syntax `+<command>`. To open a file directly in Goyo, you can run `vim file +Goyo`.

**Comment by ipsod** [comment]
@jxpp I think that answers the title of my question, but not the body of it.  I want to open a Goyo tab from inside of vim (not from the command line), without the intermediate step of first opening that file, which always makes it so that the file is open in two places - the original window, and the Goyo window.

**Comment by junegunn** [comment]
Goyo was designed to be a "mode" that you turn on and off on the current editing buffer. You can think of it as a `:tab split` with (or should we say without?) bells and whistles.

So the behavior you described is not supported. Consider writing a custom Vim function/command that automates the workflow.  Also using `:bd` to close the Goyo tab will have a similar, albeit not identical, effect.
