### ISSUE TITLE
Goyo freezes computer when leaving GVim

### ISSUE THREAD

**Issue by tlhunter** [junegunn/goyo.vim#203]
My computer freezes for several seconds when alt tabbing away from GVim when Goyo is activated.

It's more likely to happen if I move around the buffer several times with `jk` before tabbing out. The freeze happens regardless of the app being switched to.

I'll try to come up with a simple repro when I get the time. Here's my vimrc file:
https://github.com/tlhunter/vimrc/blob/master/vimrc

`gvim --version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```

It doesn't happen when running in terminal vim, probably because there's no real concept of tabbing away.

**Comment by junegunn** [comment]
Not reproducible. Looks like a configuration issue.
