### ISSUE TITLE
Guidance on showing lightline.vim

### ISSUE THREAD

**Issue by capaldo** [junegunn/goyo.vim#212]
I tried combing through the issues but didn't see anything. Could anyone point me in the right direction on how to keep lightline.vim shown when calling Goyo?

**Comment by chuling** [comment]
> I tried combing through the issues but didn't see anything. Could anyone point me in the right direction on how to keep lightline.vim shown when calling Goyo?

```viml
function! s:goyo_enter()
  silent! call lightline#enable()
endfunction
autocmd! User GoyoEnter nested call <SID>goyo_enter()
```

**Comment by capaldo** [comment]
when I enter goyo, the lightline bar appears with gaps
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/41103209/84606141-1ed47900-ae71-11ea-8c78-be31240c214b.png">

**Comment by chuling** [comment]
> when I enter goyo, the lightline bar appears with gaps
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/41103209/84606141-1ed47900-ae71-11ea-8c78-be31240c214b.png">

It's a new buf window on top, like those on left and right, so lightline will be there.

<img width="1243" alt="tmp" src="https://user-images.githubusercontent.com/23468295/84620879-b9819600-af0b-11ea-83b1-4d9ff4f3a652.png">

check <https://github.com/junegunn/goyo.vim/blob/3e129198bba7d6b50406902002ad7d213a6cccaa/autoload/goyo.vim#L85-L106> and <https://github.com/junegunn/goyo.vim/blob/3e129198bba7d6b50406902002ad7d213a6cccaa/autoload/goyo.vim#L65-L83>.
