### ISSUE TITLE
Completion popup keeps showing in :goyo

### ISSUE THREAD

**Issue by fakeharxy** [junegunn/goyo.vim#215]
I have really, really tried to find my own solution here but I have spent an hour + so I thought I would write here. Essentially, something - potentially ultiSnips, potentially Ale, I'm not sure - still offers me autocomplete based on words already written in the document, and it's very distracting and completely against the spirit of goyo.

So I guess my question is - is there a way to disable all autocompletion/popups when entering goyo?

Thanks in advance.

**Comment by junegunn** [comment]
You can manually disable each plugin on `GoyoEnter` event.

- https://github.com/junegunn/goyo.vim#callbacks
