### ISSUE TITLE
Leaving Goyo turn ColorColumn to red

### ISSUE THREAD

**Issue by m147** [junegunn/goyo.vim#225]
Hi.

For some reason when I leave Goyo it turns the colour of ColorColumn to red (I have it set to dark grey).  Here is what I mean ...

BEFORE
![2020 06 20_01 45 49](https://user-images.githubusercontent.com/23084850/85159394-6b1c2080-b298-11ea-93d4-1d0e39406fb0.png)

AFTER
![2020 06 20_01 46 11](https://user-images.githubusercontent.com/23084850/85159446-7bcc9680-b298-11ea-8a20-c2be3b8feb0e.png)

**Comment by junegunn** [comment]
See
- https://github.com/junegunn/goyo.vim/pull/195#issuecomment-483080401
- https://github.com/junegunn/goyo.vim/issues/84#issuecomment-156299446
