### ISSUE TITLE
words split over lines

### ISSUE THREAD

**Issue by jbuencuerpo** [junegunn/goyo.vim#231]
Hi,
Awesome plugin. When I re-open a file with long lines the wrap does not respect words, and they are  split across lines. For example the word recently can be split on whatever letter, non even syllables. If I am writing that does not happen sometimes and the word go to the next line.
This is expected or it is a bug/problem with my config?
Thanks

**Comment by jbuencuerpo** [comment]
I found how to solve this on reddit by adding set linebreak and set wrap. I close the issue, but I suggest it may be default.
Thanks.
```
nnoremap <silent><leader>vv :Goyo<cr>:set linebreak<cr>:set wrap<cr>

**Comment by junegunn** [comment]
`wrap` is on by default (see `:help wrap`). So you intentionally turned it off somewhere.

**Comment by junegunn** [comment]
I recommend that you use `GoyoEnter` event for changing settings for Goyo.

https://github.com/junegunn/goyo.vim#callbacks
