### ISSUE TITLE
Run Goyo inside a Panel or Split

### ISSUE THREAD

**Issue by chrisburnor** [junegunn/goyo.vim#239]
It would be awesome if there were a straightforward mode for Goyo to be invoked but only for the current panel or split.

If I'm working on a long document, it is helpful to the the outline or footnotes available in a separate panel for quick reference.

**Comment by samarulmeu** [comment]
Any news on the implementation of this? I just discovered that I cannot use a vertical split with goyo. 

Thank you!

**Comment by junegunn** [comment]
If you look at how Goyo works, you'll see that this isn't really possible.

Goyo opens a new tab and creates 4 invisible splits around the window in the middle. So there are actually 5 split windows on the screen you're seeing.

<img width="1710" alt="image" src="https://github.com/junegunn/goyo.vim/assets/700826/ac350250-dc8f-4b93-bfc7-9093f9f2593f">

It's a bit of a gimmick.

AFAIK, there's no native way to add paddings to a window in Vim.
