### ISSUE TITLE
Hide showbreak / don't offset wrapped lines

### ISSUE THREAD

**Issue by savchenko** [junegunn/goyo.vim#240]
Currently wrapped lines have an offset:
![image](https://user-images.githubusercontent.com/300146/98050171-087f8780-1e29-11eb-87b2-62272ef25f01.png)

I have tried `set showbreak=''`, but this still leaves the gap.  
Is there a way to keep text nicely justified and preserve the wrapping?

**Comment by junegunn** [comment]
Try `set showbreak=` (no quotes)
