### ISSUE TITLE
Airline(?) suddenly returning after losing and gaining focus

### ISSUE THREAD

**Issue by antaxiom** [junegunn/goyo.vim#245]
When I lose and gain focus sometimes I see my airline come back, but I also see this scratch line surround the top and sides of my airline. This is odd and unexpected, I had many plugins so it's possible there's one that triggered this.

This is the current situation:
![image](https://user-images.githubusercontent.com/40070530/104043103-b56fdb00-51b1-11eb-83d8-939db5cc590c.png)

This is how it usually looks:
![image](https://user-images.githubusercontent.com/40070530/104043264-f1a33b80-51b1-11eb-8196-cac951092ee2.png)

**Comment by tgturner** [comment]
Looks like this is a dup of #198

**Comment by antaxiom** [comment]
Seems to be the case, I couldn't find an issue for this so I made it. Thank
you.

**Comment by tgturner** [comment]
By the way, there is a suggested fix in that issue that worked for me on MacOS with neovim and airline

**Comment by antaxiom** [comment]
I'll try this in a moment, I'll update after trying it. Just mentioning I'm
only Linux, but it should still work.

**Comment by antaxiom** [comment]
Works perfectly, thanks.
