### ISSUE TITLE
Statusline visibility on urxvt

### ISSUE THREAD

**Issue by renodesper** [junegunn/goyo.vim#25]
I'm using lightline and already tried your trick in customization page. But I still can't hide statusline when I run goyo. 
![2014-04-23-205346_1366x768_scrot](https://cloud.githubusercontent.com/assets/807413/2778261/58469f30-caf0-11e3-9cae-638dc833e135.png)

**Comment by ajmwagar** [comment]
Still having issues on urxvt. Same as above,

Vim 8
Ubuntu
Urxvt-Unicode-256
