### ISSUE TITLE
Is there a g:goyo_offset? Or any other way to set offsets permanently?

### ISSUE THREAD

**Issue by michael-odonovan** [junegunn/goyo.vim#252]
Want to do what this does:
:Goyo 50%+25%x50%-25%
but put it in my config.
Any ideas?
thanks

**Comment by michael-odonovan** [comment]
Sorry for asking, got this to work, posting here for anyone else.
Maybe would be great if there was g:goyo_offset=+15% as well if possible.

autocmd! User GoyoEnter nested call <SID>goyo_enter()
function! s:goyo_enter()
	" width+offsetxheight
	Goyo 60%+15%x100%
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()

**Comment by junegunn** [comment]
You can just write shortcut commands like so

```vim
command! MyGoyo Goyo 50%+25%x50%-25%
```

**Comment by michael-odonovan** [comment]
thanks your a diamond!
