### ISSUE TITLE
Unknown Function: Running Goyo on Ubunti 22.04

### ISSUE THREAD

**Issue by vinn2010** [junegunn/goyo.vim#267]
I recently switched my config from mac to ubuntu. All other plugins work fine but when I launch Goyo, I get the following error:

`Cannot source a directory: "~/.config/nvim/autoload/goyo.vim"`                                                                                                                     
`E117: Unknown function: goyo#execute`

I looked at the directory for autoload, everything seems to look fine. 

Any ideas?

**Comment by veetase** [comment]
I got this error, too, on macOS Ventura 13.1

**Comment by junegunn** [comment]
I suggest that you use a plugin manager to instead of manually managing plugin files.

**Comment by vinn2010** [comment]
i used vim plug.
