### ISSUE TITLE
goyo doesn't hide lualine

### ISSUE THREAD

**Issue by indeedwatson** [junegunn/goyo.vim#270]
I opened this issue on lualine but was told it was on goyo's part, https://github.com/nvim-lualine/lualine.nvim/issues/806

Here's what it looks like when I'm using lualine and I activate goyo:

https://user-images.githubusercontent.com/10749504/185532551-2bdd45fa-033e-4592-aafb-54b9d23bcc11.png

There's an API to hide lualine: https://github.com/nvim-lualine/lualine.nvim#disabling-lualine

**Comment by junegunn** [comment]
You can use the API to hide it on callbacks.

See https://github.com/junegunn/goyo.vim#callbacks

I can't update Goyo every time a new statusline plugin comes up.

**Comment by miki725** [comment]
neovim solution:

```lua
local goyo_group = vim.api.nvim_create_augroup("GoyoGroup", { clear = true })
vim.api.nvim_create_autocmd("User", {
    desc = "Hide lualine on goyo enter",
    group = goyo_group,
    pattern = "GoyoEnter",
    callback = function()
        require("lualine").hide()
    end,
})
vim.api.nvim_create_autocmd("User", {
    desc = "Show lualine after goyo exit",
    group = goyo_group,
    pattern = "GoyoLeave",
    callback = function()
        require("lualine").hide({ unhide = true })
    end,
})
```
