### ISSUE TITLE
set goyo mode only for markdown files ?

### ISSUE THREAD

**Issue by Bercio** [junegunn/goyo.vim#36]
Is there a way (or if there isn't, I'd like to suggest it) to enable goyo mode only for markdown files and disable it when switching to some other files ? 
I tried `au Filetype markdown Goyo` but it doesn't work, doesn't have any effect.

**Comment by abarax** [comment]
Just a note for anyone coming across this in the future (like I did)

`autocmd BufEnter * call s:auto_goyo()`

Changing this to BufEnter here is essential I think because the function will not run if opening files that already have existing buffers.

**Comment by tylerlmz1** [comment]
I also can't make Goyo only start for markdown files, but I didn't find any workable solution for me.

I tried this and it worked.

```
autocmd Filetype markdown :Goyo | :Goyo
autocmd BufRead,BufNewFile *.md :Goyo
```

i know this is a weird solution, I didn't understand why it worked, just sharing for anyone that might need it.

I'm using Vim version 8.2.1897
