### ISSUE TITLE
Question: Activate Goyo doesn't disable NERDTree

### ISSUE THREAD

**Issue by die4live** [junegunn/goyo.vim#37]
Mac OS X 10.9.4, MacVim 7.4, installed NERDTree and NERDTreeTabs plugins

When activate Goyo, NERDTree still exists, wanner know it's a problem of myself or not. However, NERDTree is reopened after quitting if been manually disabled in Goyo mode. Thanks!

**Comment by rajus0007** [comment]
Thanks . It helped me .
