### ISSUE TITLE
Display error with vim plugin golden-ratio

### ISSUE THREAD

**Issue by kepbod** [junegunn/goyo.vim#40]
I installed vim plugin [golden-ratio](https://github.com/roman/golden-ratio), and I got a stark new line (as shown below). I figured out that it is caused by the golden-ratio plugin, but I don't know how to disable it before start Goyo automatically. My vim config about Goyo is https://github.com/kepbod/ivim/blob/master/vimrc#L677. Could you help me? Thanks!

![snapshot](https://cloud.githubusercontent.com/assets/1172557/3841580/42d2d79a-1e2e-11e4-82df-e126202662de.png)

**Comment by Pablo1107** [comment]
I had this problem when I added golden-ratio, which make an empty file off-center (this didn't happen on a filled file) and a series of tildes as presented in this screenshot.

![imagen](https://user-images.githubusercontent.com/17091659/53710140-a03dfe80-3e1a-11e9-8830-8172c54512ca.png)

Adding this to the function I used to open Goyo solves it perfectly.
> execute "normal \<Plug>(golden_ratio_toggle)"

Thanks @junegunn
