### ISSUE TITLE
Typing lag

### ISSUE THREAD

**Issue by mclearc** [junegunn/goyo.vim#50]
I've noticed that when using Goyo I often experience fairly extreme typing lag (sometime up to around five seonice discussions before words appear on the screen) with documents of any substantial length (say 10000 words or more). Is this an expected problem? 

I write mainly in pandoc-flavor markdown and use the vim-pandoc syntax highlighting plugin.

**Comment by junegunn** [comment]
No, it's not expected. It is possible that some other plugins or settings are causing the problem. Have you tried without other plugins?

**Comment by mclearc** [comment]
It doesn't seem to be my other plugins. I notice no slowdown on similar length documents in other vim instances. It appears to happen primarily when I am in tmux. Have you had any problems with the interaction between the two?

**Comment by mclearc** [comment]
It might also be an issue when I have many different buffers open. I've tried quitting all buffers and restarting the document, after which there is no lag.

**Comment by junegunn** [comment]
Could you try profiling your Vim session?

See: http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow

**Comment by mclearc** [comment]
I will, thanks. I'm having trouble reduplicating the problem now. My 
suspicion though is that it might be due to git-gutter. I'll report back 
after profiling.

–––

Colin McLear
colinmclear.net
mclear@fastmail.com

**Comment by mclearc** [comment]
I'm closing this until I can adequately reduplicate the issue. I'll let you know what the profile says when I do so. Thanks for the help, and the plugin!

**Comment by junegunn** [comment]
Okay, thanks!
