### ISSUE TITLE
Scrolloff settings seems not to work in Goyo

### ISSUE THREAD

**Issue by alexlafroscia** [junegunn/goyo.vim#52]
I'm trying to set up a writing environment as close to [iA Writer](http://www.iawriter.com/mac/) as possible, and Goyo gets me about 98% of the way there.  The one thing that I can't get right, and the one thing that is actually important to me, is that the current line remains centered on the screen.  I've heard about the

```
set scrolloff=999
```

trick, but it doesn't seem to be working.  No what I do, it seems that my `scrolloff` setting stays around 3 or so.  Is there some trick to getting it to play nicely with Goyo?

**Comment by junegunn** [comment]
I'm on my mobile, so I can't test it but you shouldn't have problem setting the option inside Goyo window. Try this and let me know what it says

```vim
:set scrolloff=999
:verbose set scrolloff?
```
