### ISSUE TITLE
Map to default size: ctrl+w =

### ISSUE THREAD

**Issue by llfm** [junegunn/goyo.vim#53]
Hello,

There's some possibility to [add](https://github.com/junegunn/goyo.vim/blob/master/plugin/goyo.vim#L148) (or workaround) the map `ctrl+w =`, which defines the window default size.

Thanks.

**Comment by junegunn** [comment]
Thanks for the suggestion. I'll look into it when I get some time.

**Comment by junegunn** [comment]
Updated. Thanks!
