### ISSUE TITLE
Losing highlights after leaving Goyo mode

### ISSUE THREAD

**Issue by oblitum** [junegunn/goyo.vim#54]
I use the [vim-operator-highlight](https://github.com/Valloric/vim-operator-highlight). When I enter Goyo mode, it's still active, after leaving I miss all operator coloring.

**Comment by junegunn** [comment]
`doautocmd Syntax` on `GoyoLeave` event will re-do the highlighting.

**Comment by oblitum** [comment]
@junegunn shouldn't something like this be default behavior? I guess no one expects to get back in a different state than when entering Goyo mode.

**Comment by junegunn** [comment]
Let's put aside Goyo; If you change your color scheme, you'll realize that the plugin loses its highlight groups, no one expects that, right? You should file an issue on the plugin so that it reruns itself on `ColorScheme` event.

**Comment by oblitum** [comment]
@junegunn ok, thanks for the explanation.
