### ISSUE TITLE
Use autoload-ing

### ISSUE THREAD

**Issue by edkolev** [junegunn/goyo.vim#55]
Thank you for this plugin!

Are you interested in making goyo.vim use vim's autoload-ing? I've modified goyo.vim here https://github.com/edkolev/goyo.vim. Basically, I just

* moved plugin/goyo.vim => autoload/goyo.vim
* changed the `command Goyo call s:goyo(..)` => `command Goyo call goyo#execute(..)`

I haven't run into any issues yet, but I suspect there may be some lurking around. In particular, I suspect some autocommands may not be working properly.

BTW yes, I know this is completely unnecessary if you're using a lazy-loading plugin manager like vim-plug :)

Again, thanks!

**Comment by junegunn** [comment]
Thanks. I've been putting off doing it forever. Let me know if you see any issue.
