### ISSUE TITLE
Prevent Goyo to close on `bd`

### ISSUE THREAD

**Issue by zanona** [junegunn/goyo.vim#56]
hey @junegunn, first of all, thanks so much for Goyo. 
It is all I ever wanted in a text editor and I am happy I found this for Vim.

There is one small thing which is bothering a little bit.
That happens when calling `:Goyo`, I am taken to Goyo mode as expected, so all my tabs are affect. That's all great, however, when closing one tab with `bd` Goyo closes and the next tab previously open is now back to normal vim mode.

How do I prevent Goyo to close when closing a tab with `bd`?

thanks in advance

**Comment by junegunn** [comment]
> I am taken to Goyo mode as expected, so all my tabs are affect

Technically this is not true. `:Goyo` commands opens the current buffer in a new tab without changing/affecting any other pre-existing tab. They're left intact. It's essentially same as `:tab split`, except Goyo centers the window by surrounding it with 4 invisible windows around it. You can open another buffer in Goyo mode (`:e FILENAME`), but if you close (or `q` or `bd`) the window, the entire Goyo tab will be closed as well. It's the way Goyo operates and unfortunately there's no way around it.

**Comment by zanona** [comment]
@junegunn thanks for the explanation.

So as far as I could understand, Goyo is always a single view that represents and switches through tabs without really changing tabs _(but just changing Goyo current view contents)_. By using `bd` will kill the Goyo tab itself with the current opened file. But the other "physical" tabs were never really touched.

Considering this, is there any other way to just remove that file from Goyo (simulating `bd`) while still be able to keep using the same Goyo view for the remaining files?

**Comment by junegunn** [comment]
> Considering this, is there any other way to just remove that file from Goyo (simulating bd) while still be able to keep using the same Goyo view for the remaining files?

You can open the other files with `:e [filename]` or `:b [buffer-no]` command (or `[buffer-no]CTRL-^`) without leaving Goyo view. Do you really have to remove the file? I almost never have needed to `bd` with `set hidden`.

**Comment by zanona** [comment]
You are correct. It was just because of the convenience of using `bd` and `bp` which becomes a bit complicated when several files are open. Perhaps I can try to get used to other ways to switch between files without these commands and get the same quick response.

**Comment by junegunn** [comment]
Ah okay, I understand. That makes sense. If you use some sort of fuzzy finder plugin it should provide a command for switching buffers (e.g. CtrlPBuffer of ctrlp.vim. I'm using [my own implementation using fzf](https://github.com/junegunn/dotfiles/blob/master/vimrc#L1299)), perhaps you may find it useful.

**Comment by zanona** [comment]
Thanks so much for the tip @junegunn, actually it was great to look through you `.vimrc` file, lots of useful commands there — thanks for sharing.

I will try the fuzzy finder as well. In the mean time, one good thing I figured out on how to close tabs and keep Goyo active, is to move to the next tab (`bd`) and then do a `bd <filename|buffer_number>` when the tab specified is not being displayed, Goyo will still active and simply drop the tab below which is also functional.
In fact, the nice thing about the `bd filename` option is that when pressing <kbd>tab</kbd>, vim also autocompletes the possible options, which makes it even faster. ;)

**Comment by zanona** [comment]
hey @junegunn just updating this since I have found a solution that would stop Goyo of crashing when using `bd` command.

I have found [this article](http://vim.wikia.com/wiki/VimTip165) mentioning how to do it. — The first script using the method name `Bclose` is the one that works, not the second version.

Basically it will delete the current buffer without affecting the current window layout which was the main reason for Goyo to crash. Additionally I have re-mapped the command `bd` with the `Bclose` function provided in the script with the below. Everything works nicely now :smiley: 

```vim
cabbrev bd <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'Bclose' : 'e')<CR>
```

**Comment by junegunn** [comment]
Hi, also note that since 8b74a60, Goyo does not close on `bd`.

**Comment by zanona** [comment]
That's nice, however a bit odd, because yesterday, vim was crashing several types when using `bd` with Goyo then I decided to update to the latest from master branch but unfortunately it didn't solve the problem? Quite intriguing, I will keep using with the new Bclose plugin enabled and see if I still have that issue.

**Comment by lucasmsoares96** [comment]
> hey @junegunn just updating this since I have found a solution that would stop Goyo of crashing when using `bd` command.
> 
> I have found [this article](http://vim.wikia.com/wiki/VimTip165) mentioning how to do it. — The first script using the method name `Bclose` is the one that works, not the second version.
> 
> Basically it will delete the current buffer without affecting the current window layout which was the main reason for Goyo to crash. Additionally I have re-mapped the command `bd` with the `Bclose` function provided in the script with the below. Everything works nicely now 😃
> 
> ```viml
> cabbrev bd <c-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'Bclose' : 'e')<CR>
> ```
I worked around this problem like this:
```
nnoremap <leader>q :b # <bar> :bd! # <CR>
```
