### ISSUE TITLE
Opening and closing location list /quick-fix window breaks goyo

### ISSUE THREAD

**Issue by jeetsukumaran** [junegunn/goyo.vim#57]
Basically, opening a location list/quick fix window, makes the goyo window smaller (as expected), but after closing the goyo window it does not grow back again. This happens in vertical and horizontal split mode.

**Comment by junegunn** [comment]
Thanks for the report but I couldn't reproduce the problem as shown below:

![quickfix](https://cloud.githubusercontent.com/assets/700826/6054053/9bce6ca6-ad2b-11e4-97e2-d3d6c33394b1.gif)

The following is the vimrc used for the above test:

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/goyo.vim'
Plug 'junegunn/vader.vim'
call plug#end()
```

However, I wouldn't be surprised if Goyo doesn't work well with splits, especially the sidebars from the other plugins. Goyo basically is a big abuse of vim splits so I don't expect it to work with other splits. :relieved:

**Comment by jeetsukumaran** [comment]
Thanks for looking into it. Appreciate it!
