### ISSUE TITLE
Random '.' at the bottom right corner of Goyo mode

### ISSUE THREAD

**Issue by scwood** [junegunn/goyo.vim#59]
![screen shot 2015-02-21 at 2 39 56 am](https://cloud.githubusercontent.com/assets/9126138/6313617/113d7bbe-b973-11e4-95f1-08cfab0b4005.png)

I have this really annoying period character in the bottom right of my screen... I'm sure it's something on my end. Do you have any idea how I could troubleshoot this? 

Only shows up in Goyo, here's my [vimrc](https://github.com/scwood/dotfiles/blob/master/vimrc), if that helps.

**Comment by junegunn** [comment]
Well, I don't know, there's really no shortcut. Disable everything and start with the minimum,

```vim
call plug#begin()
Plug 'junegunn/goyo.vim'
call plug#end()
```
and incrementally reenable stuff until you find the culprit.

**Comment by junegunn** [comment]
What does `:verbose hi statusline` say?

**Comment by scwood** [comment]
![screen shot 2015-02-21 at 11 04 33 am](https://cloud.githubusercontent.com/assets/9126138/6315249/7d3572d6-b9b9-11e4-9556-0d3b436d1409.png)

I'll move to a minimal vimrc and try to replicate it.

**Comment by scwood** [comment]
![screen shot 2015-02-21 at 11 08 13 am](https://cloud.githubusercontent.com/assets/9126138/6315255/f96fd6c0-b9b9-11e4-9b65-87b02b189e86.png)

With that minimal .vimrc it's still showing. Deleted .vim folder and reinstalled the plugin and everything.

**Comment by junegunn** [comment]
Vim version?

**Comment by scwood** [comment]
7.4 compiled with homebrew.

**Comment by junegunn** [comment]
Ah, yes it's reproducible, and I completely forgot about this.

Goyo tries to hide the dot in the statusline by setting the color of it to the same color as the background. However, if your plugin does not explicitly set background color (`echo synIDattr(synIDtrans(hlID('Normal')), 'bg')` returns -1 or empty string), Goyo cannot do so and simply sets the color to `g:goyo_bg` (undocumented) or `black`. See here: https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L109-L112

The workaround is to use a color scheme that sets that background color for `Normal` highlight group, or you set it yourself.

**Comment by scwood** [comment]
What would be the syntax for setting the background color for the normal highlight group? Is it something I could just add to my colorscheme or my vimrc?

**Comment by junegunn** [comment]
Since you're using terminal

```vim
highlight Normal ctermbg=ANSICOLORCODE
```
should do. I recommend putting it in your color scheme.

**Comment by scwood** [comment]
So with that snippet, it still doesn't seem to be changing to the background color chosen?

Just to get it going I threw it in my .vimrc and picked a random color and the period is still showing up in a different color:

![screen shot 2015-02-21 at 12 09 31 pm](https://cloud.githubusercontent.com/assets/9126138/6315534/aaea43c4-b9c2-11e4-81ff-e09874469089.png)

**Comment by junegunn** [comment]
What if you put it in your color scheme?

**Comment by scwood** [comment]
![screen shot 2015-02-21 at 12 14 12 pm](https://cloud.githubusercontent.com/assets/9126138/6315579/31a2a046-b9c3-11e4-89bf-ae4c316df991.png)

233 is the correct color. Still there after quitting and reloading. Does it matter where I stick it in the colorscheme?

**Comment by junegunn** [comment]
Hmm, not sure. Could you test with another color scheme, such as `junegunn/seoul256.vim`?

**Comment by junegunn** [comment]
And please check the output of `:echo synIDattr(synIDtrans(hlID('Normal')), 'bg')`

**Comment by scwood** [comment]
Echo output is in the left corner.
![screen shot 2015-02-21 at 12 26 58 pm](https://cloud.githubusercontent.com/assets/9126138/6315627/f26de780-b9c4-11e4-9c08-42078b780b7b.png)

**Comment by junegunn** [comment]
Huh, very strange. It's not reproducible on my terminal.

```sh
vim -Nu <(cat << EOF
call plug#begin()
Plug 'junegunn/goyo.vim'
Plug 'junegunn/seoul256.vim'
call plug#end()
colo seoul256
EOF
)
```

Still reproducible with the above?

**Comment by scwood** [comment]
Still there... :(
![screen shot 2015-02-21 at 12 35 34 pm](https://cloud.githubusercontent.com/assets/9126138/6315657/2766c21c-b9c6-11e4-96d0-59c90bb4b4fd.png)

**Comment by junegunn** [comment]
You see, ctermfg == ctermbg, so the text shouldn't be visible. And the tildes (~) on the buffer should be invisible as well (`:hi nontext`), but they're showing for some unknown reason. Are you still testing it on both iterm2 and terminal.app?

**Comment by scwood** [comment]
There's the nontext. Terminal.app is working correctly now, so I guess it's an iterm issue?
![screen shot 2015-02-21 at 12 43 53 pm](https://cloud.githubusercontent.com/assets/9126138/6315684/500991bc-b9c7-11e4-9517-da25565d34da.png)

**Comment by scwood** [comment]
Turning down the contrast slider all the way on my iterm2 settings seemed to fix it. I feel like an idiot. Thanks for your help!
![screen shot 2015-02-21 at 12 48 08 pm](https://cloud.githubusercontent.com/assets/9126138/6315701/e7807d12-b9c7-11e4-84db-4c87dbb5e99e.png)

**Comment by junegunn** [comment]
Ha, no problem.
