### ISSUE TITLE
Syntax highlighting not restored on some plugins

### ISSUE THREAD

**Issue by jftaas** [junegunn/goyo.vim#60]
When using goyo with some plugins (vimwiki in particular), some of the custom syntax that the plugin implements do not get restored (eg. bold/italic text). As a workaround, I added the following line in goyo_off to refresh the syntax highlighting:
```
execute 'syn on | syn off'
```

**Comment by junegunn** [comment]
Possibly related: https://github.com/junegunn/goyo.vim/issues/54
I don't use the plugin you mentioned so I can't tell, but check if changing color schemes while using the plugin reproduce the same problem (w/o Goyo)

**Comment by jftaas** [comment]
Thanks for the heads up; they are related. Closing this one.

**Comment by junegunn** [comment]
https://github.com/Valloric/vim-operator-highlight/pull/7
