### ISSUE TITLE
needs option to disable margins and extra surrounding buffers

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/goyo.vim#61]
i'm quite fond of goyo, but I don't like the margins and extra surrounding buffers it creates around the text, it would be very nice to have the option to disable them entirely

**Comment by junegunn** [comment]
But, setting the margins around the window is the main responsibility of Goyo. If you do not want that, you probably should check out much simpler alternatives like https://github.com/bilalq/lite-dfm.

/cc @bilalq
