### ISSUE TITLE
Increase the spacing between splits

### ISSUE THREAD

**Issue by chishaku** [junegunn/goyo.vim#62]
The horizontal split has the appearance of one buffer even though there are two.  Is there a way to increase the spacing between the two? 

Likewise, increasing the spacing between two vertically split buffers would also be preferable in my case.

**Comment by junegunn** [comment]
No, as far as I know it's not allowed in Vim. Goyo simply hides the statuslines and vertical-bar between the splits which take up single line/column between the buffers.

- Without Goyo
![nogoyo](https://cloud.githubusercontent.com/assets/700826/6728966/8e2ed0e2-ce71-11e4-8c45-ed39e825fdfe.png)

- With Goyo (there's still single separators between the buffers, but they're hidden)
![goyo](https://cloud.githubusercontent.com/assets/700826/6728965/8e2b3d4c-ce71-11e4-89d9-235984c79e0c.png)

**Comment by chishaku** [comment]
Understood, thanks.
