### ISSUE TITLE
Not preserving highlighting when leaving

### ISSUE THREAD

**Issue by octref** [junegunn/goyo.vim#66]
Hi junegunn thanks for your Vim libraries, I like them a lot :smiley: 

Here is a problem with Goyo I've run into.
When I toggle Goyo off, the highlight options are not preserved.

I'm using YCM with the following highlight config:
```
hi Pmenu ctermfg=240 ctermbg=254
hi PmenuSel ctermfg=254 ctermbg=240
```

When I enter Vim, `:Goyo` to toggle Goyo on, the highlight is there
![image](https://cloud.githubusercontent.com/assets/4033249/7194792/b45cf6ae-e483-11e4-84f7-565c34a0a9b4.png)

Then when I toggle it off, all the highlight configs are resetted:
![image](https://cloud.githubusercontent.com/assets/4033249/7194802/d6a632f2-e483-11e4-80fa-57277cf381a5.png)
---
![image](https://cloud.githubusercontent.com/assets/4033249/7194822/1683ad1e-e484-11e4-873e-e18c21de1987.png)

I think #51 is also caused by this problem.

Thanks again!

**Comment by junegunn** [comment]
You lose the highlighting also when you change color scheme, right?
Then it's related to #54. You'll have to set up a `ColorScheme` autocmd for reapplying the config.

**Comment by octref** [comment]
Right. I put my `highlight` functions into a function and autocmd'ed it to `GoyoLeave` and now it works great.

Thanks! Maybe you can add a note for this behavior in `Readme.md` or the `Customization` wiki? It's a little bit unintuitive.
