### ISSUE TITLE
Weird vertical bar in Distraction-Free mode

### ISSUE THREAD

**Issue by halfo** [junegunn/goyo.vim#67]
### Problem

In DF (Distraction-Free) mode, a weird vertical bar is appearing. I'm sure it is a vertical split bar. However, if I enter in insert mode it is gone. It reappears when I enter in DF mode again!

### Screenshot

![oie_q4joxo0litvp](https://cloud.githubusercontent.com/assets/2076914/7443185/ea83f420-f159-11e4-8c5b-287a1c5867ea.png)

### Background

I wanted to set SignColumn always visible in DF mode. So I'm adding a dummy sign whenever I'm entering in DF mode and removing it whenever I leaves. Here is the code

```vim
function! s:goyo_enter()
:sign define dummy
:execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
endfunction

function! s:goyo_leave()
:execute 'sign unplace 9999 buffer=' . bufnr('')
:sign undefine dummy
endfunction

autocmd User GoyoEnter nested call <SID>goyo_enter()
autocmd User GoyoLeave nested call <SID>goyo_leave()
```

That weird bar stops appearing if I remove this code segment from my vimrc.

**Comment by junegunn** [comment]
Must be caused by another plugin or some configuration. Cannot reproduce with the following vimrc:

```vim
set rtp+=~/.vim/plugged/goyo.vim
function! s:goyo_enter()
  sign define dummy
  execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
endfunction

function! s:goyo_leave()
  execute 'sign unplace 9999 buffer=' . bufnr('')
  sign undefine dummy
endfunction

autocmd User GoyoEnter nested call <SID>goyo_enter()
autocmd User GoyoLeave nested call <SID>goyo_leave()
```

```
vim -Nu mini-vimrc
```

> if I enter in insert mode it is gone

You should probably check `:autocmd InsertEnter` and `:autocmd InsertLeave`.

**Comment by halfo** [comment]
With that mini-vimrc, this is what it looks like now...

![screenshot](https://cloud.githubusercontent.com/assets/2076914/7444565/6b7aec96-f1aa-11e4-97e6-535b937e9655.png)

BTW, I've managed to overcome this by setting LineNr's colors to my colorscheme's background color:
```vim
function! s:goyo_enter()
:sign define dummy
:execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
hi LineNr gui=none guibg=#1c1c1c guifg=#1c1c1c cterm=none ctermbg=234 ctermfg=234
endfunction

function! s:goyo_leave()
:execute 'sign unplace 9999 buffer=' . bufnr('')
:sign undefine dummy
endfunction

autocmd User GoyoEnter nested call <SID>goyo_enter()
autocmd User GoyoLeave nested call <SID>goyo_leave()
```
And this works iff that `hi LineNr gui...` is inside goyo_enter() function!

**Comment by junegunn** [comment]
![l](https://cloud.githubusercontent.com/assets/700826/7444839/d99d6268-f1d1-11e4-90c1-16b5ed826647.png)
![d](https://cloud.githubusercontent.com/assets/700826/7444838/d99d6f7e-f1d1-11e4-9caa-15f27eb53cbb.png)

Well, this is what I see on my terminal (iterm2 with dark and light color themes). You probably should check your terminal configuration or try different terminal emulator.

**Comment by halfo** [comment]
Yeah, I also think it's something terminal related. Well, thanks for your time and such awesome plugin!
