### ISSUE TITLE
Display issue with the `list` option enabled

### ISSUE THREAD

**Issue by mrzool** [junegunn/goyo.vim#70]
I use `set list` and `set listchars=eol:¬` in my vimrc to display end of lines with non-printing characters. 

When I activate Goyo, those eol non-printing chars turn black (they're usually dimmed-out) and clutter the screen near the right margin and on the far left. It looks like this: 

![goyo](https://cloud.githubusercontent.com/assets/6874363/7881854/bf0d5fd0-0607-11e5-8bf6-72c7e54d9645.png)

Any hint about how to solve this?

**Comment by junegunn** [comment]
What does `:verb hi nontext` say?

**Comment by mrzool** [comment]
Normally it's:

```
NonText        xxx term=bold ctermfg=239 gui=bold guifg=#75715E
	Last set from ~/.vim/bundle/molokai/colors/molokai.vim
```

With Goyo enabled:

```
NonText        xxx term=bold ctermfg=0 gui=bold guifg=#75715E
	Last set from ~/.vim/bundle/goyo.vim/autoload/goyo.vim
```

**Comment by junegunn** [comment]
Okay, what about `:verb hi normal`?

**Comment by mrzool** [comment]
I set that one explicitly in my .vimrc with `hi Normal guibg=NONE ctermbg=NONE` because transparency.

The output of `:verbose` is

```
Normal         xxx ctermfg=252 guifg=#F8F8F2
	Last set from ~/.vimrc
```

By the way, this setting gets lost every time I exit Goyo, I always need to `:source $MYVIMRC` to get my transparent background back. Was unsure whether to open another issue about it.

**Comment by junegunn** [comment]
Goyo hides those elements by setting the foreground color of them to the same color as the background. So it's not possible for transparent background, and you'll have to manually toggle listchars on GoyoEnter and GoyoLeave.

Since Goyo overrides certain colors during its initialization, it has to restore the colors, and to do that, it simply reloads the current color scheme. So that's why the colors you manually set are restored on exit. There are a couple of ways to avoid this:
1. Do it again on User GoyoLeave event
2. Hook your code to ColorScheme autocmd so that it's applied whenever you switch/reload color schemes.

**Comment by mrzool** [comment]
Oooh I see, that makes total sense. I'll do as you suggest, thanks a lot!

**Comment by nathyong** [comment]
This still appears to be an issue, but I managed to work around it by using `set listchars=` in the GoyoEnter autocmd, and resetting listchars to the old value on GoyoLeave:

```
function! s:goyo_enter()
  silent !tmux set status off
  set nolist
  set listchars=
  set noshowmode
  set noshowcmd
endfunction

function! s:goyo_leave()
  silent !tmux set status on
  set list
  set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮,trail:·
  set showmode
  set showcmd
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
```

**Comment by nathyong** [comment]
After some quick testing, it seems that listchars *outside the main window* remain shown. If you `set nolist` then the listchars inside the main window do not get drawn, but listchars in the spacing buffers still appear if `background=light`. When `background=dark` the characters are still there, but hidden (by virtue of being the same colour as the background).

I suspect that this has some relation to the way that Goyo overrides the colours in the colourscheme upon activation.

**Comment by chuling** [comment]
The reason which causing list chars disappear is that Goyo resets the highlight group for NonText and causes NonText colored with the same fg and bg (That's why listchars "disappear", in fact, they are still there).

How to solve it:

```viml
" replace #6c767f with your favorite
function! s:patch_nontext()
  highlight! NonText guifg=#6c767f guibg=NONE gui=NONE
endfunction
autocmd! User GoyoEnter nested call <SID>patch_nontext()
```
