### ISSUE TITLE
Existing Goyo overrides personnal highlight conf

### ISSUE THREAD

**Issue by etiennebatise** [junegunn/goyo.vim#72]
Hi,

I am using gvim with the solarized colorscheme which set the `Folded` group to be `underlined`. I don't like that so in my vimrc I wrote : `highlight Folded gui=bold`

Then,  going into _Goyo_ mode works fine but exiting **re-underline** the folds.

I've noticed a similar weird behavior with `Comments`. I put the in italic in my vimrc file with `highlight Comment gui=italic` but something they just go **normal** going in or out of Goyo mode.

I hope I'm clear :smile:

**Comment by etiennebatise** [comment]
Ok, solution is here https://github.com/junegunn/goyo.vim/issues/44

**Comment by junegunn** [comment]
Okay, I think a better way to handle this is to attach your `highlight` code to `ColorScheme` autocmd so that it's applied whenever you switch/reload color schemes.
