### ISSUE TITLE
set wrap and linebreak would be useful

### ISSUE THREAD

**Issue by richardwonka** [junegunn/goyo.vim#74]
When invoking Goyo, I end up with long lines, the ends of which are invisible.

As I am writing text, I would like to be able to see what I've been writing.

:set wrap
:set linebreak

fixes this.

I suggest making this behaviour default.

For the record I am using current neovim.

**Comment by junegunn** [comment]
Hi, you can override the default settings to your liking using `GoyoEnter`.
See https://github.com/junegunn/goyo.vim#callbacks.

**Comment by richardwonka** [comment]
I have done that, I'm saying it would be a sane default, as I can't see how scrolloff lines are good in a writing environment where there is more space than needed.

**Comment by junegunn** [comment]
I see. In my case, I use `textwidth` to automatically hard-wrap lines, so those settings are not necessary. And `wrap` is on by default, so the lines will not be cutoff unless the user *disabled it on purpose*. And I don't think `linebreak` is something we should enforce, it should be up to the user's preference.

Goyo has been around for almost two year by now, so please understand that I'm reluctant to change default settings at this point.
