### ISSUE TITLE
SignColumn changes color after leaving :Goyo

### ISSUE THREAD

**Issue by frace** [junegunn/goyo.vim#76]
I setup a custom color for the highlight group `SignColumn`:

    highlight clear SignColumn
    highlight link SignColumn LineNr

After leaving Goyo it seems like the colors are reset to their default values and the `SignColumn` becomes grey.

**Comment by junegunn** [comment]
See https://github.com/junegunn/goyo.vim/search?q=highlight

**Comment by frace** [comment]
Thanks for the hint. Binding it to `autocmd ColorScheme` does help a little bit. That means after leaving Goyo the color changes back to its original values as soon as I move the cursor.
