### ISSUE TITLE
Returning from Goyo changes background=dark to background=light

### ISSUE THREAD

**Issue by azag0** [junegunn/goyo.vim#78]
What the title says. Does it make sense or is it some plugin collision? As a workaround, I have

```vim
autocmd! User GoyoLeave
autocmd  User GoyoLeave nested set background=dark
```

**Comment by junegunn** [comment]
Check `:verbose set background`.

**Comment by atommixz** [comment]
no `:set background?` showing same, but something wrong

1. open file: http://rghost.ru/68nM9jpw5.view
2. :Goyo http://rghost.ru/8Wf7rr7YG.view
3. :Goyo http://rghost.ru/7867VmmHP.view

**Comment by azag0** [comment]
After entering Goyo, `:verbose set background?` says `background=dark, last set from ~/.vimrc`. After leaving Goyo, it says `background=light, last set from MacVim.app/Contents/Resources/vim/runtime/colors/default.vim`. So is it the case that Goyo does not restore the previous state but rather loads a default one? I guess there is no general solution to this problem.

**Comment by junegunn** [comment]
Goyo reloads the current color scheme on exit. That's all. You'll see that background becomes `light` if you `:colo default` even without Goyo. If you don't like it, use the workaround provided by @azag0 or choose a color scheme that does keep the option value intact. My seoul256 is one example.

**Comment by azag0** [comment]
I actually don't use any color scheme, that is I use the default one and set `background=dark` manually in `.vimrc`, which is what is recommended in `:h 'background'`. But I see there is no way for Goyo to know that so I'll be using the `GoyoLeave` construct.
