### ISSUE TITLE
Vertical split size 

### ISSUE THREAD

**Issue by nobe4** [junegunn/goyo.vim#80]
Hello,
First, thanks a lot for your plugin, combined with [vim-pencil](https://github.com/reedes/vim-pencil) it makes all my prose-writing so much more delightful. :+1: 

I encounter an issue when I try to open a vertical split while in the Goyo tab, as you can see in the following picture : 
![screen shot 2015-08-25 at 15 04 53](https://cloud.githubusercontent.com/assets/2452791/9467245/96887428-4b3a-11e5-8784-ab63a54f2c69.png)

Instead of splitting the window size in two, it split the display zone in two.

Do you know if that is a normal behaviour, and if not, what can I do to solve it ?

Thanks,

**Comment by junegunn** [comment]
Yeah it's the expected behavior since Goyo was not designed to be used with splits. You can try resizing the central window before splitting it with `:Goyo 160` or with something like <kbd>40</kbd><kbd>CTRL-W</kbd><kbd>></kbd>.

**Comment by junegunn** [comment]
Hmm, <kbd>40</kbd><kbd>CTRL-W</kbd><kbd>></kbd> doesn't seem to work as expected when the central window is split. `:Goyo WIDTH` works fine though.

**Comment by nobe4** [comment]
Thanks for the answer !
