### ISSUE TITLE
Feature Request: Sane Keybindings

### ISSUE THREAD

**Issue by FranzSkuffka** [junegunn/goyo.vim#81]
HJKL jumps over lines, which is usually confusing because we have no line numbers.

**Comment by junegunn** [comment]
I don't think I follow you. Please be more specific.

**Comment by FranzSkuffka** [comment]
Consider the following:
Line one is soft wrapped. We not have line numbers displayed in goyo.
Whe my cursor is on the word 'line' of line one and I press 'j' the cursor jumps to to the word 'line' on line two. However line two is displayed on the third row which makes me assume that when i press 'j', I will in fact go to row two, the wrapped part of line one.
<pre><code>
line one one one one one one one one one one one one one one one one
one one one one one one one
line two two two two two two two two two two two 
</code> </pre>

There is a solution to this on [wikia](http://vim.wikia.com/wiki/Move_through_wrapped_lines)

**Comment by junegunn** [comment]
Okay, I see, thanks for the explanation. But it has never been an issue to me, which means, I don't think it needs be the default.

- I usually use Goyo when editing markdown files in which I hard-wrap lines with `textwidth`
- With `j` or `k` jumping over line, I can realize that the line is soft-wrapped. I would get the impression that the line is not soft-wrapped if Goyo implicitly sets the mappings and find it rather confusing. You see, we all have different habits and tastes. It's really hard to reach unanimous consensus.
- You can enable line numbers with `let g:goyo_linenr = 1`
- `GoyoEnter` and `GoyoLeave` provide unlimited flexibility

**Comment by FranzSkuffka** [comment]
Ok, thank you for your thoughts on this. Pretty much expected this already but still wanted to suggest it.
