### ISSUE TITLE
goyo breaks after CTRL-W O

### ISSUE THREAD

**Issue by MichaelMackus** [junegunn/goyo.vim#83]
So far loving goyo.vim

Noticed a strange bug, if I hit "CTRL-w O" (only window), goyo seems to "break" in that the goyo plugin seems to not center properly. If I hit my goyo keybind (for :Goyo 120), then I get a bunch of terminal errors:

![2015-10-12-094119_1355x569_scrot](https://cloud.githubusercontent.com/assets/737162/10433283/7471163c-70c5-11e5-9bca-946ea7000262.png)

**Comment by junegunn** [comment]
Interesting. Thanks for reporting. Pressing `CTRL-W CTRL-O` clears the surrounding windows, then there's no way but to just restart Goyo session. I'll push a simple patch.

**Comment by MichaelMackus** [comment]
Thanks! No more errors :)
