### ISSUE TITLE
Toggling goyo not properly sourcing .vimrc?

### ISSUE THREAD

**Issue by pruett** [junegunn/goyo.vim#84]
When I toggle goyo, using `:Goyo` from Vim's command line, it loads as expected, when i repeat the command, `:Goyo`, I'm returned to "normal" Vim, but it doesn't seem to source the `.vimrc` correctly as I'm losing some styles, and I'm forced to re-source my `.vimrc`

Does this make sense? Any thoughts?

**Comment by junegunn** [comment]
> I'm losing some styles

I assume that you "lose" those styles even when you simply switch color schemes or reload the current one, is it true?

**Comment by pruett** [comment]
![screen shot 2015-11-12 at 8 59 14 pm](https://cloud.githubusercontent.com/assets/794809/11136883/a2a00de6-8980-11e5-9cf1-2be86cdbfb42.png)

my regular colorscheme with a few alterations

![screen shot 2015-11-12 at 8 59 56 pm](https://cloud.githubusercontent.com/assets/794809/11136893/b42d84e4-8980-11e5-849d-f3c20f50433b.png)

goyo looks awesome :smile: 

![screen shot 2015-11-12 at 9 00 10 pm](https://cloud.githubusercontent.com/assets/794809/11136899/bdb476a8-8980-11e5-8d5b-f24d4e6eea07.png)

switching back exposes some unwanted color configs

**Comment by pruett** [comment]
> I assume that you "lose" those styles even when you simply switch color schemes or reload the current one, is it true?

I do have some additional color/ui settings after the line 16 (see above)...those are the styles that aren't being applied. is this the wrong way to tweak a colorscheme in your opinion?

**Comment by junegunn** [comment]
No, nothing wrong with that. You're losing colors here since Goyo reloads the current color scheme on exit. Just make sure those colors are re-applied when you switch color schemes using autocmd like follows.

```vim
augroup my-colors
  autocmd!
  autocmd ColorScheme * hi LineNr ...
  autocmd ColorScheme * hi FoldColumn ...
augroup END

colorscheme lucius
```

**Comment by junegunn** [comment]
A function would be cleaner.

```vim
function! s:patch_colors()
  hi LineNr ...
  hi FoldColumn ...
endfunction

augroup my-colors
  autocmd!
  autocmd ColorScheme * call s:patch_colors()
augroup END

colorscheme lucius
```

**Comment by junegunn** [comment]
Another one :)

```vim
function! s:patch_lucius_colors()
  hi LineNr ...
  hi FoldColumn ...
endfunction

autocmd! ColorScheme lucius call s:patch_lucius_colors()

colorscheme lucius
```

**Comment by pruett** [comment]
@junegunn wow, thanks!, my vim-fu is terrible, i need to learn more about `autogroup` and functions, this seems to work!
