### ISSUE TITLE
Error when exiting goyo

### ISSUE THREAD

**Issue by mrzool** [junegunn/goyo.vim#86]
I get the following error when exiting goyo:

    E127: Cannot redefine function <SNR>1_goyo_leave: It is in use

This happens when I exit goyo both with `:q` and `:Goyo`. 

It's been this like this for a couple of weeks.

This is the relevant part of my `vimrc`:

```    
" Goyo settings
function! s:goyo_enter()
  silent !tmux set status off
  set noshowmode
endfunction

function! s:goyo_leave()
  silent !tmux set status on
  source $MYVIMRC
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
```

Thanks for any help.

**Comment by junegunn** [comment]
The error message looks pretty obvious. Try using `exists('*s:goyo_leave')` condition not to redefine the function.

**Comment by mrzool** [comment]
Forgive my ignorance, but I can't figure it out. Where should I use `exists('*s:goyo_leave')` exactly? Also, I'm interested in knowing why is this happening, since I basically just copy-pasted the settings recommended in the docs. Thanks.

**Comment by junegunn** [comment]
> since I basically just copy-pasted the settings recommended in the docs

It's because you added `source $MYVIMRC` to your function. See, the error message is clear; `s:goyo_leave` reloads your .vimrc which defines `s:goyo_leave` itself. So `s:goyo_leave` is "in use", and it's consequently redefining itself, and vim does not like that. What I'm suggesting is this:

```vim
if !exists('*s:goyo_leave')
  function! s:goyo_leave()
    silent !tmux set status on
    source $MYVIMRC
  endfunction
endif
```

**Comment by mrzool** [comment]
All clear now, Thanks a lot!
