### ISSUE TITLE
Missing SignColumn background when entering Goyo

### ISSUE THREAD

**Issue by oblitum** [junegunn/goyo.vim#89]
I'm using the [Apprentice](https://github.com/romainl/Apprentice) colorscheme, its gutter color have a darker background color than normal text background, which I like and rely on to copy to colors of other highlighting groups.

When entering Goyo mode the gutter gets the same background as normal text, losing its original background. This gets messier because I've used the original gutter background for other stuff.

Any option to preserve the SignColumn background?

My Goyo setup:

```vim
" Goyo Setup {{{
let g:goyo_width = 120
let g:goyo_margin_top = 2
let g:goyo_margin_bottom = 2

function! s:goyo_enter()
    silent !tmux set status off
endfunction

function! s:goyo_leave()
    silent !tmux set status on
endfunction

au! User GoyoEnter
au! User GoyoLeave
au  User GoyoEnter nested call <SID>goyo_enter()
au  User GoyoLeave nested call <SID>goyo_leave()

nnoremap <leader>g :Goyo<cr>
" }}}
```

**Comment by junegunn** [comment]
You'll have to manually restore the color with `hi SignColumn ctermbg=...` command in GoyoEnter callback.

**Comment by oblitum** [comment]
well, saving it to restore later seems like a hassle, since highlighting groups are not as easy to manipulate as an ordinary variable, I'd like they were...

I've patched the plugin locally and removed the ocorrence of SignColumn in it. It would be nice to have some option for what should not be tranquilized.

**Comment by junegunn** [comment]
Point taken. But I'm not planning to add more configuration knobs to this project. It is possible to come up with a helper function that makes the process easier without changing Goyo.
