### ISSUE TITLE
Video about Goyo on YouTube.

### ISSUE THREAD

**Issue by petrowsky** [junegunn/goyo.vim#90]
Just in case you wanted to know. Did a short video about Goyo here.

https://www.youtube.com/watch?v=CbMIi1BkxmE

**Comment by junegunn** [comment]
Very nice, I enjoyed it, thanks for sharing :)
The problem you mentioned at the end of the video I think is related to #84. Check it out.

**Comment by petrowsky** [comment]
Awesome, that fixed it up.

The key was knowing that you're calling the color scheme. I guess I could have spent the time and looked at the code. :) Nice plugin! You're helping me replace yet another piece of software with vim.
