### ISSUE TITLE
Error upon :Goyo in Neovim

### ISSUE THREAD

**Issue by mcchrish** [junegunn/goyo.vim#92]
Using the latest Neovim build:
```
Error detected while processing function <SNR>2_lod_cmd..goyo#execute..<SNR>33_goyo_on..<SNR>33_tranquilize..<SNR>33_set_color:
line    2:
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
E421: Color name or number not recognized: ctermfg=#282828
E421: Color name or number not recognized: ctermbg=#282828
```

Here's a minimal vimrc:
```vim
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

call plug#begin('~/.config/nvim/plugged')
Plug 'morhetz/gruvbox'
Plug 'AlessandroYorba/Alduin'
let g:alduin_Shout_Windhelm = 1
Plug 'junegunn/goyo.vim'
nnoremap <silent> <leader>- :Goyo<cr>
call plug#end()

colorscheme gruvbox
" colorscheme alduin
set background=dark
```

I think the culprit is `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` due to the recent change in neovim https://github.com/neovim/neovim/wiki/Following-HEAD#20160204.
Works when that line is commented out.

**Comment by junegunn** [comment]
Thanks for the heads up.

This is the code we should fix:
https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L36-L37
It's pretty easy to fix it, we can just decide to set `guifg` instead of `ctermfg` if the color value starts with `#` regardless of `gui_running` and I will do it for now. But I'm not completely sure if it's the "correct" way to handle this. What if in the future Vim decides to support truecolors in terminal and `ctermfg=#fffff` becomes legitimate?

/cc @justinmk

**Comment by justinmk** [comment]
> What if in the future Vim decides to support truecolors in terminal and ctermfg=#ffffff becomes legitimate?

If Vim decides to support truecolor in the terminal, it's very unlikely the approach will differ from how Neovim does it: re-using guifg/guibg for true color-enabled terminals is vastly less disruptive than any other approach I can think of. Changing ctermfg/ctermbg to support RGB would mean colorschemes need to be rewritten and/or updated, and/or new colorschemes will not be backwards-compatible with old Vims. 

With the approach Neovim is using, colorschemes and plugins can set `cterm{fg,bg}` & `gui{fg,bg}` in a single `:highlight` call, and the editor decides which pair to use. Is there a reason goyo doesn't want to do this? Example:

    :hi ctermbg=black ctermfg=red guibg=#00000 guifg=#abc123

**Comment by junegunn** [comment]
This is what it does:
```vim
let bg = synIDattr(synIDtrans(hlID('Normal')), 'bg')
let gui = a:color =~ '^#' " was has('gui_running')
execute printf("hi ToBeHidden %sfg=%s", gui ? 'gui' : 'cterm', bg)
```
And of course I don't want to parse the output of `:hi`.

**Comment by justinmk** [comment]
I see. Then the change you made is the best approach, and for the reasons above I think it is reasonably future-proof.

**Comment by darribas** [comment]
Hello, I have a similar problem using Goyo in Oni, which is built on neovim. I just installed it from their latest release and I get a similar error. Was there any proposed solution? I will say also that one can ignore the messages and Goyo seems to work OK, but the error messages come up every time one activates Goyo. Thank you very much.

**Comment by justinmk** [comment]
@darribas It's not really necessary nor appropriate to enable `termiguicolors` in Oni. My comment was targeted at @junegunn  or other contributors here if they want to try to improve goyo.vim to more reliably detect a Neovim GUI.

**Comment by darribas** [comment]
Ahh, OK. Excellent! I'll keep using it. It's really not a problem once you skip over the error messages. Thank you very much for `Goyo`, it's a such a neat piece of software!
