### ISSUE TITLE
Enabling line numbers on autocdm call

### ISSUE THREAD

**Issue by Granitas** [junegunn/goyo.vim#93]
I'm trying to enable line numbers for Goyo however when Goyo is executed with autocmd it doesn't call the `goyo_enter()`  

    " Goyo plugin
    function! s:goyo_enter()
       set number
    endfunction
    autocmd! User GoyoEnter nested call <SID>goyo_enter()
    " augroups
    augroup mdg
      autocmd!
      autocmd FileType markdown,md,text
                  \ Goyo 80
                  \ | <more stuff here>
    augroup END

Am I missing something ? if I use `Goyo` instead of `Goyo 80` it isn't executed at all.

**Comment by junegunn** [comment]
I know it's not obvious but if you want to disable `number`, just set `let g:goyo_linenr = 1` instead of setting up GoyoEnter callback. It'll work. Related: #31
