### ISSUE TITLE
A little less minimal

### ISSUE THREAD

**Issue by habitullence** [junegunn/goyo.vim#94]
Great plugin!

How would I get it to me a little less minimal? I basically just want to limit the width, i.e., keep airline, line numbers,etc.

**Comment by junegunn** [comment]
- "keep airline"
    - Fancy statusline plugins don't work well with goyo, so no.
- "line numbers"
    - `let g:goyo_linenr = 1`
- Other customization
    - See https://github.com/junegunn/goyo.vim#callbacks
