### ISSUE TITLE
Auto-resizing after creating and destroying new windows

### ISSUE THREAD

**Issue by sencer** [junegunn/goyo.vim#95]
Hi,

I am using goyo when working with markdown files. A problem I am facing is when I am using it with a dictionary plugin (https://github.com/sencer/wordnet.vim) to lookup some words. This plugin creates a window to look up the definitions, and destroys it after looking up. But this messes with the height of goyo windows. Is there a way around this?

**Comment by junegunn** [comment]
<kbd>CTRL-W</kbd><kbd>=</kbd> will reset the size of the Goyo window. So maybe you can set up a buffer local mapping in the wordnet window to close it and trigger the mapping (`normal <c-w>=`) afterwards. However, note that <kbd>CTRL-W</kbd><kbd>=</kbd> will resize the window to its initial size, which may not be what you want if you have manually resized it. But after all, Goyo was not designed to work well with plugins that creates splits.
