### ISSUE TITLE
Compatibility with neovim + fzf

### ISSUE THREAD

**Issue by rahmatawaludin** [junegunn/goyo.vim#97]
I'm using neovim as suggested to get fzf on my bottom screen (not fullscreen). But, when I activate goyo and activate fzf, the fzf buffer won't closed. 

Step to reproduce:

1. Use neovim
2. Open file
3. Activate fzf, then press `esc` when picking file
4. Fzf buffer not closed

Here is what I got:

Opening file
![Opening file](https://cloud.githubusercontent.com/assets/1274849/13370891/0c5dd19c-dd4a-11e5-8723-951957df80ed.png)

Open fzf
![Open fzf](https://cloud.githubusercontent.com/assets/1274849/13370893/1712beb8-dd4a-11e5-885e-306b8fbf5073.png)

pressing `esc` on fzf
![pressing `esc` on fzf](https://cloud.githubusercontent.com/assets/1274849/13370895/23e51104-dd4a-11e5-9a00-1a8c3707b147.png)

What should I do to fix this?

**Comment by junegunn** [comment]
Actually it's not that fzf window is still open, but the invisible buffer below the central window is affected and resized (related #95). When that happens, you can hit <kbd>CTRL-W</kbd><kbd>=</kbd> to reset the size of the Goyo window. I'll see if it can be automatically done when I get some time.

**Comment by MichaelMackus** [comment]
:+1: 

This also completely breaks Goyo with any full screen FZF window :(
