### ISSUE TITLE
Colors not properly recovered after leaving Goyo

### ISSUE THREAD

**Issue by oblitum** [junegunn/goyo.vim#98]
I use a terminal with transparency support, and I set Vim to inherit transparency using this on my `.vimrc`:

```vim
hi! Normal ctermbg=none
hi! NonText ctermbg=none
```

This works fine for the colorscheme I use ([Apprentice](https://github.com/romainl/Apprentice)). When I enter Goyo mode, the transparency is still active, but when leaving Goyo it does something that removes transparency and set the colorscheme's background to an opaque color.

**Comment by oblitum** [comment]
By the way, putting those command on goyo_leave fix this, I'm just not sure it should be there or Goyo should be fixed regarding this. Feel free to close it in case you don't consider this a bug.

**Comment by junegunn** [comment]
Actually this is closely related to the conversation we had before (#54). The point is that Goyo reloads your colorscheme on exit and your custom colors are reverted by that.
See #84 for the solution.

**Comment by oblitum** [comment]
@junegunn thanks, good solution.
