### ISSUE TITLE
Filetype-specific highlighting lost when leaving Goyo

### ISSUE THREAD

**Issue by chreekat** [junegunn/goyo.vim#99]
First, this is something I am noticing with my own filetype plugin, [chreekat/vimin](https://github.com/chreekat/vimin), and perhaps there is a bug in *that* plugin.

After leaving Goyo, the buffer loses filetype-specific highlighting. The syntax items still exist, but their highlighting is cleared.

Here's an image demonstrating this behavior with the "inNA" syntax item, defined and highlighted in [vimin/syntax/in.vim](https://github.com/chreekat/vimin/blob/master/syntax/in.vim).

![image](https://cloud.githubusercontent.com/assets/538538/13382351/635c955e-de27-11e5-9d62-29a826c82804.png)

`:hi inNA` shows 

    inNA           xxx ctermfg=5

before/during Goyo, and

    inNA           xxx cleared

after. The syntax item shows up in `:syn` at all times.

**Comment by junegunn** [comment]
See #54 and #84.

Goyo reloads the current color scheme on exit and the adjustments your plugin made are reverted by that. Which means that you will be able to reproduce the problem just by switching color schemes even without Goyo. Consider reapplying the custom highlights on `ColorScheme` autocmd.

**Comment by chreekat** [comment]
Thanks for the info! I will fix up my plugin.
